#!/bin/bash

source rpi.inc

IMAGE=rpi.img
DISK=$(losetup -f)
IMAGEDIR=imagetmp

rm -rf $IMAGE.*

status "generate image"

fallocate -l 1G $IMAGE
fdisk $IMAGE <<EOF
o
n
p


+64M
t
c
n
p



w
EOF

status "copy files to image"

losetup -P $DISK $IMAGE

mkfs.vfat ${DISK}p1
mkfs.ext4 -F ${DISK}p2

mkdir $IMAGEDIR
mount ${DISK}p2 $IMAGEDIR
mkdir $IMAGEDIR/boot
mount ${DISK}p1 $IMAGEDIR/boot

rsync -a $ROOTFS/ $IMAGEDIR

umount ${DISK}p1
umount ${DISK}p2

rm -rf $IMAGEDIR

losetup -d $DISK

status "compress image"
tar -acf $IMAGE.tar.bz2 $IMAGE
