#!/bin/bash

source rpi.inc

mkdir -p $ROOTFS
source packages
PACKAGES=${PACKAGES[@]}

MIRROR_BASE=$(grep -v "#" mirrors.base| head -n 1)
MIRROR_RPI=$(grep -v "#" mirrors.raspberrypi| head -n 1)

qemu-debootstrap --arch=armhf \
		 --variant=minbase \
		 stable \
		 "$ROOTFS" \
	         "http://$MIRROR_BASE/debian"

status "root passwd"
chroot "$ROOTFS" /bin/sh -c "echo root:root| chpasswd"

status "gpg key"
wget http://archive.raspberrypi.org/debian/raspberrypi.gpg.key -O $ROOTFS/raspberrypi.gpg.key
chroot "$ROOTFS" apt-key add raspberrypi.gpg.key
rm $ROOTFS/raspberrypi.gpg.key

status "sources.list"
cp sources.list.template sources.list
sed -i -e "s|BASE_URL|$MIRROR_BASE|g" sources.list
sed -i -e "s|RPI_URL|$MIRROR_RPI|g" sources.list
cp sources.list $ROOTFS/etc/apt/sources.list

status "install package"
chroot "$ROOTFS" /bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get update"
chroot "$ROOTFS" /bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get -y install $PACKAGES"
chroot "$ROOTFS" /bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get clean"

status "rasp start config"
cp config.txt cmdline.txt $ROOTFS/boot/

status "network"
cp interfaces $ROOTFS/etc/network/

status "fstab"
cp fstab $ROOTFS/etc/

status "ssh"
cp sshd_config $ROOTFS/etc/ssh/

status "time"
chroot "$ROOTFS" systemctl enable systemd-timesyncd
chroot "$ROOTFS" systemctl disable hwclock-save

status "rm qemu"
rm $ROOTFS/usr/bin/qemu-arm-static

#status "compress"
#tar -acf $ROOTFS.tar.bz2 $ROOTFS
